// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_ebrel_cpp
Rcpp::List run_ebrel_cpp(const std::vector<int>& E_int, const std::vector<double>& C, const std::vector<double>& SD, const std::vector<int>& D, const std::vector<double>& SxH, const std::vector<double>& O, const std::vector<int>& LM_int, int dim_x, int dim_y, int n_h, int n_s, double sentinel, Rcpp::List opt);
RcppExport SEXP _ebrel_run_ebrel_cpp(SEXP E_intSEXP, SEXP CSEXP, SEXP SDSEXP, SEXP DSEXP, SEXP SxHSEXP, SEXP OSEXP, SEXP LM_intSEXP, SEXP dim_xSEXP, SEXP dim_ySEXP, SEXP n_hSEXP, SEXP n_sSEXP, SEXP sentinelSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type E_int(E_intSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type SD(SDSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type SxH(SxHSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type O(OSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type LM_int(LM_intSEXP);
    Rcpp::traits::input_parameter< int >::type dim_x(dim_xSEXP);
    Rcpp::traits::input_parameter< int >::type dim_y(dim_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< double >::type sentinel(sentinelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(run_ebrel_cpp(E_int, C, SD, D, SxH, O, LM_int, dim_x, dim_y, n_h, n_s, sentinel, opt));
    return rcpp_result_gen;
END_RCPP
}
// generate_X0_A_R
Rcpp::IntegerVector generate_X0_A_R(const std::vector<uint8_t>& U, int n_h, int dim_x, int dim_y, double base_prob, int seed);
RcppExport SEXP _ebrel_generate_X0_A_R(SEXP USEXP, SEXP n_hSEXP, SEXP dim_xSEXP, SEXP dim_ySEXP, SEXP base_probSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< int >::type dim_x(dim_xSEXP);
    Rcpp::traits::input_parameter< int >::type dim_y(dim_ySEXP);
    Rcpp::traits::input_parameter< double >::type base_prob(base_probSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_X0_A_R(U, n_h, dim_x, dim_y, base_prob, seed));
    return rcpp_result_gen;
END_RCPP
}
// ebrel_omp_thread_limit
int ebrel_omp_thread_limit();
RcppExport SEXP _ebrel_ebrel_omp_thread_limit() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ebrel_omp_thread_limit());
    return rcpp_result_gen;
END_RCPP
}
// ebrel_omp_for_threads
int ebrel_omp_for_threads();
RcppExport SEXP _ebrel_ebrel_omp_for_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ebrel_omp_for_threads());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ebrel_run_ebrel_cpp", (DL_FUNC) &_ebrel_run_ebrel_cpp, 13},
    {"_ebrel_generate_X0_A_R", (DL_FUNC) &_ebrel_generate_X0_A_R, 6},
    {"_ebrel_ebrel_omp_thread_limit", (DL_FUNC) &_ebrel_ebrel_omp_thread_limit, 0},
    {"_ebrel_ebrel_omp_for_threads", (DL_FUNC) &_ebrel_ebrel_omp_for_threads, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ebrel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
