# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ebrel_cpp <- function(E_int, C, SD, D, SxH, O, LM_int, dim_x, dim_y, n_h, n_s, sentinel, opt) {
    .Call(`_ebrel_run_ebrel_cpp`, E_int, C, SD, D, SxH, O, LM_int, dim_x, dim_y, n_h, n_s, sentinel, opt)
}

generate_X0_A_R <- function(U, n_h, dim_x, dim_y, base_prob, seed) {
    .Call(`_ebrel_generate_X0_A_R`, U, n_h, dim_x, dim_y, base_prob, seed)
}

ebrel_omp_thread_limit <- function() {
    .Call(`_ebrel_ebrel_omp_thread_limit`)
}

ebrel_omp_for_threads <- function() {
    .Call(`_ebrel_ebrel_omp_for_threads`)
}

